GET localhost:4000/api/v1/users
###

GET localhost:4000/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzk4MjE5MzAsImV4cCI6MTY3OTgzNjMzMH0.PHduSQaD1EpT53vziOhGgvebbfuOXAvQYOKCqY-9wKc

###

POST localhost:4000/api/v1/users/register
Content-Type: application/json

{
  "fullName": "monkey",
  "email": "monkey12@gmail.com",
  "password": "1234"
}
###

POST localhost:4000/api/v1/users/login
Content-Type: application/json

{
  "email": "no@gmail.com",
  "password": "123"
}

###

POST localhost:4000/api/v1/users/login
Content-Type: application/json

{
  "email": "monkey12@gmail.com",
  "password": "1234"
}

###
