GET localhost:4001/api/v1/products/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODAzMTY3NDgsImV4cCI6MTY4MDMzMTE0OH0.AC6CzEvaWwOj0IIp5o8-epQ43wvjWHUcCTy6qcQfJJk
###

GET localhost:4001/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODAzMTY3NDgsImV4cCI6MTY4MDMzMTE0OH0.AC6CzEvaWwOj0IIp5o8-epQ43wvjWHUcCTy6qcQfJJk
Content-Type: application/json

{
  "category": "food"
}

###

POST localhost:4001/api/v1/products/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODAzMTY3NDgsImV4cCI6MTY4MDMzMTE0OH0.AC6CzEvaWwOj0IIp5o8-epQ43wvjWHUcCTy6qcQfJJk
Content-Type: application/json

{
  "product_id": 1,
  "product_name": "banana",
  "product_price": "6"
}

###
